export const shortcuts = {
    "none": "",
    "reviews":"/reviews",
    "services":"/services",
    "home":"/",
    "article":"/article",
    "about":"/about",
    "contact":"/contact",
    "works":"/works",
    "blog":"/blog",
    "search":"/search",
    "stoves":"/stoves",
    "fireplaces":"/fireplaces",
    "management":"/management",
    "settings":"/settings",
    "me":"/me",
    "login":"/login",
    "register":"/register",
    "logout":"/logout",
    "forgot":"/forgot",
    "password":"/password",
    "privacy":"/privacy",
    "terms":"/terms",
    "edit" : "/edit",
    "delete":"/delete",
    "page":"/page",
} as const;

export const shortcutsService = {
    "consultation":"/photo-service1",
    "mentoring":"/photo-service2",
    "individual-session":"/photo-service3",
    "agreement":"/photo-service4",
    "photo-edition":"/photo-service5",
    "communions": "/photo-service6",
    "birthdays-and-eightings":"/photo-service7",
    "halfways":"/photo-service8",
    "proms":"/photo-service9",
    "wedding-afterpaty-and-parties":"/photo-service10",
    "home-and-close-parties":"/photo-service11",
    "teanagers-events-and-clubs":"/photo-service12",
    "christening":"/photo-service13",
    "school-events":"/photo-service14",
    "gym-sessions":"/photo-service15",
    "jubilees-and-anniversaries":"/photo-service16",
} as const;